MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
      CONV_BODY: "R-101-FPN"
      OUT_CHANNELS: 512
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    RETURN_FC_FEATS: True
    PREDICTOR: "FPNPredictor"
    MLP_HEAD_DIM: 2048
    NUM_CLASSES: 1601
    # For evaluation we don't need attribute head
    ATTR: False
  RESNETS:
    STRIDE_IN_1X1: False
    NUM_GROUPS: 64
    WIDTH_PER_GROUP: 4
DATASETS:
  TRAIN: ("visual_genome_train",)
  TEST: ("vqa_train",)
DATALOADER:
  NUM_WORKERS: 8
  SIZE_DIVISIBILITY: 32
