MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/25093814/X-152-32x8d-IN5k.pkl"
  BACKBONE:
      CONV_BODY: "R-152-FPN"
      OUT_CHANNELS: 512
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    RETURN_FC_FEATS: True
    PREDICTOR: "FPNPredictor"
    MLP_HEAD_DIM: 2048
    NUM_CLASSES: 1601
    # VQA GENOME SPECIFIC STUFF
    ATTR: False
  RESNETS:
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
DATASETS:
  TRAIN: ("visual_genome_train", "visual_genome_val")
  TEST: ("visual_genome_val",)
DATALOADER:
  NUM_WORKERS: 8
